services:

  # خدمة الـ PHP (البرنامج بتاعك)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthify-backend-api
    restart: unless-stopped
    volumes:
      - ./:/var/www
    networks:
      - healthify-net

  # خدمة الـ Nginx (السيرفر اللي هيستقبل الطلبات)
  web:
    image: nginx:alpine
    container_name: healthify-nginx
    restart: unless-stopped
    ports:
      - "8000:80" # هتفتح الـ API من localhost:8000
    volumes:
      - ./:/var/www
      - ./docker-config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - healthify-net

  # خدمة الـ MySQL (الداتابيز)
  db:
    image: mysql:8.0
    container_name: healthify-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - healthify-net

networks:
  healthify-net:
    driver: bridge

volumes:
  dbdata: