services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthify-backend-api
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - app-storage:/var/www/storage/app
      - app-public:/var/www/public
    depends_on:
      healthify-db:
        condition: service_healthy
    networks:
      - healthify-net

  web:
    image: nginx:alpine
    container_name: healthify-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./docker-config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - app-public:/var/www/public:ro
    depends_on:
      - app
    networks:
      - healthify-net

  healthify-db:
    image: mysql:8.0
    container_name: healthify-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: healthify
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: healthify_user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - healthify-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

networks:
  healthify-net:
    driver: bridge

volumes:
  dbdata:
  app-storage:
  app-public: